name: actions  # The name of the workflow in the "Actions" tab of the repo.
run-name: ${{ github.actor }} is learning GitHub Actions  #  Prints "henryj320 is learning GitHub Actions".
on: [push]  # Trigger to activate the workflow.
jobs:
  check-bats-version:  # Defines a job named "check-bats-version".
    runs-on: ubuntu-latest  # Runs on a fresh VM hosted by GitHub.
    steps:  # Eeach step that the job runs.
      - uses: actions/checkout@v3  # Use this whenever your workflow runs against the repo's code.
      - uses: actions/setup-node@v3  # Installs the Version 14 of Node.js
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v  # Outputs the version of bats
